# Generated by Django 2.0.3 on 2018-05-05 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('location', '0002_auto_20180505_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='floor',
        ),
        migrations.AddField(
            model_name='room',
            name='office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='location.Office'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='building',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.Office'),
        ),
    ]
