# Generated by Django 2.0.3 on 2018-03-21 06:33

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('contact_info', models.TextField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=128, unique=True)),
                ('image', models.ImageField(default='device.png', storage=django.core.files.storage.FileSystemStorage(location='./media/images/devices'), upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('room', models.CharField(max_length=512)),
                ('comment', models.TextField()),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='./media/images/location'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('image', models.ImageField(default='manufacturer.png', storage=django.core.files.storage.FileSystemStorage(location='./media/images/manufacturers'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.Location')),
            ],
        ),
    ]
