# Generated by Django 2.0.3 on 2018-03-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20180326_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='image',
            field=models.ImageField(default='manufacturer.png', upload_to=''),
        ),
    ]
