# Generated by Django 2.0.3 on 2018-03-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_auto_20180326_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
