# Generated by Django 2.0.3 on 2018-03-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_auto_20180326_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='contact_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
