# Generated by Django 2.0.3 on 2018-04-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_auto_20180326_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
