# Generated by Django 2.0.3 on 2018-04-07 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_auto_20180404_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='devices.Office'),
        ),
    ]
