# Generated by Django 2.0.3 on 2018-04-07 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_contractor_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='office',
        ),
    ]
