# Generated by Django 2.0.3 on 2018-04-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0015_remove_contractor_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
