# Generated by Django 2.0.3 on 2018-04-09 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0016_place_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Floor',
        ),
    ]
