# Generated by Django 2.0.3 on 2018-04-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0017_auto_20180409_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floor',
            old_name='room',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='image',
        ),
        migrations.AddField(
            model_name='floor',
            name='plan',
            field=models.ImageField(default='images/plans/default_plan.png', upload_to='images/plans'),
        ),
    ]
