# Generated by Django 2.0.3 on 2018-04-12 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_room_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='building',
            new_name='floor',
        ),
    ]
