# Generated by Django 2.0.3 on 2018-04-12 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0021_auto_20180412_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='places',
        ),
        migrations.AddField(
            model_name='place',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='devices.Room'),
        ),
    ]
