# Generated by Django 2.0.3 on 2018-04-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0022_auto_20180412_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='x',
            field=models.IntegerField(default=0, verbose_name='coordinate x'),
        ),
        migrations.AddField(
            model_name='place',
            name='y',
            field=models.IntegerField(default=0, verbose_name='coordinate y'),
        ),
    ]
