# Generated by Django 2.0.3 on 2018-04-27 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0023_auto_20180412_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='x',
            new_name='left',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='y',
            new_name='top',
        ),
    ]
