# Generated by Django 2.0.3 on 2018-05-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0026_auto_20180504_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorynumberprefix',
            name='devices',
            field=models.ManyToManyField(to='devices.Device'),
        ),
        migrations.AddField(
            model_name='inventorynumberprefix',
            name='inventory_number_mask',
            field=models.CharField(default='ddd', max_length=128),
        ),
    ]
