# Generated by Django 2.0.3 on 2018-05-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0027_auto_20180504_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorynumberprefix',
            name='prefix',
            field=models.CharField(max_length=512),
        ),
    ]
