# Generated by Django 2.0.3 on 2018-05-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0028_auto_20180504_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorynumberprefix',
            name='prefix',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
