# Generated by Django 2.0.3 on 2018-03-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer_spares', '0003_auto_20180326_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge',
            name='image',
            field=models.ImageField(default='cartridge.png', upload_to='images/cartridges'),
        ),
        migrations.AlterField(
            model_name='cartridge',
            name='in_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cartridge',
            name='urls',
            field=models.ManyToManyField(blank=True, to='devices.Url'),
        ),
        migrations.AlterField(
            model_name='spare',
            name='contractors',
            field=models.ManyToManyField(blank=True, to='devices.Contractor'),
        ),
        migrations.AlterField(
            model_name='spare',
            name='image',
            field=models.ImageField(default='spare.png', upload_to='images/spares'),
        ),
        migrations.AlterField(
            model_name='spare',
            name='in_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spare',
            name='urls',
            field=models.ManyToManyField(blank=True, to='devices.Url'),
        ),
    ]
