# Generated by Django 2.0.3 on 2018-03-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer_spares', '0004_auto_20180326_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='KindOfSpare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
            ],
        ),
    ]
