# Generated by Django 2.0.3 on 2018-03-26 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printer_spares', '0005_kindofspare'),
    ]

    operations = [
        migrations.AddField(
            model_name='spare',
            name='kind_of_spare',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='printer_spares.KindOfSpare'),
        ),
    ]
