# Generated by Django 2.0.3 on 2018-03-26 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printer_spares', '0006_spare_kind_of_spare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spare',
            name='name',
        ),
        migrations.AlterField(
            model_name='spare',
            name='kind_of_spare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='printer_spares.KindOfSpare'),
        ),
    ]
