# Generated by Django 2.0.3 on 2018-04-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('printer_spares', '0008_cartridge_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartridge',
            name='color',
            field=models.CharField(
                choices=[('black', 'black'), ('cyan', 'cyan'), ('magenta', 'magenta'), ('yellow', 'yellow'),
                         ('multicolor', 'multicolor')], default='black', max_length=32),
        ),
    ]
