# Generated by Django 2.0.3 on 2018-04-07 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('devices', '0014_contractor_office'),
        ('printer_spares', '0009_cartridge_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartridgeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_stock', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('cartridge',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='printer_spares.Cartridge')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.Office')),
            ],
        ),
        migrations.CreateModel(
            name='SpareItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_stock', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.Office')),
            ],
        ),
        migrations.RemoveField(
            model_name='spare',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='spareitem',
            name='spare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='printer_spares.Spare'),
        ),
    ]
