# Generated by Django 2.0.3 on 2018-04-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('devices', '0015_remove_contractor_office'),
        ('printer_spares', '0010_auto_20180407_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartridge',
            name='contractors',
        ),
        migrations.RemoveField(
            model_name='cartridge',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='spare',
            name='contractors',
        ),
        migrations.AddField(
            model_name='cartridgeitem',
            name='contractors',
            field=models.ManyToManyField(blank=True, to='devices.Contractor'),
        ),
        migrations.AddField(
            model_name='spareitem',
            name='contractors',
            field=models.ManyToManyField(blank=True, to='devices.Contractor'),
        ),
    ]
