# Generated by Django 2.0.3 on 2018-04-29 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('printer_spares', '0011_auto_20180407_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartridgeitem',
            name='cartridge',
        ),
        migrations.RemoveField(
            model_name='cartridgeitem',
            name='contractors',
        ),
        migrations.RemoveField(
            model_name='cartridgeitem',
            name='office',
        ),
        migrations.AlterField(
            model_name='spareitem',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.Office'),
        ),
        migrations.DeleteModel(
            name='CartridgeItem',
        ),
    ]
