# Generated by Django 2.0.3 on 2018-04-29 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('devices', '0025_auto_20180427_1802'),
        ('location', '0001_initial'),
        ('printer_spares', '0012_auto_20180429_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartridgeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_stock', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('cartridge',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='printer_spares.Cartridge')),
                ('contractors', models.ManyToManyField(blank=True, to='devices.Contractor')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.Office')),
            ],
        ),
    ]
