# Generated by Django 2.0.3 on 2018-05-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kindofhistory',
            options={'verbose_name_plural': 'Kind of History'},
        ),
    ]
