# Generated by Django 2.0.3 on 2018-05-15 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0003_auto_20180505_1835'),
        ('history', '0002_auto_20180515_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartridgeItemHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('create', 'create'), ('add', 'add')], default='create', max_length=32)),
                ('message', models.CharField(max_length=512)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.Office')),
                ('user', models.ForeignKey(on_delete=models.SET(history.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='history',
            name='kind_of',
        ),
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='KindOfHistory',
        ),
    ]
