# Generated by Django 2.0.3 on 2018-05-15 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printer_spares', '0014_auto_20180514_1415'),
        ('history', '0003_auto_20180515_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartridgeitemhistory',
            name='cartridge_item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='printer_spares.CartridgeItem'),
        ),
        migrations.AlterField(
            model_name='cartridgeitemhistory',
            name='action',
            field=models.CharField(choices=[('create', 'create'), ('income', 'income'), ('delivery', 'delivery')], default='create', max_length=32),
        ),
        migrations.AlterField(
            model_name='cartridgeitemhistory',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Office'),
        ),
    ]
