# Generated by Django 2.0.3 on 2018-05-18 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_auto_20180515_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartridgeitemhistory',
            name='time',
        ),
        migrations.AddField(
            model_name='cartridgeitemhistory',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartridgeitemhistory',
            name='action',
            field=models.CharField(choices=[('create', 'create'), ('income', 'income'), ('delivery', 'delivery'), ('consumption', 'consumption')], default='create', max_length=32),
        ),
    ]
