# Generated by Django 2.0.3 on 2018-03-21 06:33

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('image', models.ImageField(default='printer.png', storage=django.core.files.storage.FileSystemStorage(location='./media/images/printers'), upload_to='')),
                ('duplex', models.BooleanField(default=False)),
                ('network', models.BooleanField(default=False)),
                ('color', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('laser', 'laser'), ('ink', 'ink')], default='laser', max_length=32)),
                ('comment', models.TextField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.Device')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='PrinterChangeCartridgeJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('printed_sheets', models.IntegerField(verbose_name='printed sheets')),
            ],
        ),
        migrations.CreateModel(
            name='PrinterItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.TextField(max_length=32, unique=True, verbose_name='inventory number')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.Place')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='printers.Printer')),
            ],
        ),
        migrations.CreateModel(
            name='PrinterRepairJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('total_printed_sheets', models.IntegerField(verbose_name='total printed sheets')),
                ('result', models.CharField(choices=[('success', 'success'), ('fail', 'fail'), ('partial', 'partial')], default='success', max_length=32)),
                ('comment', models.TextField()),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.Contractor')),
                ('printer_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='printers.PrinterItem')),
            ],
        ),
        migrations.AddField(
            model_name='printerchangecartridgejob',
            name='printer_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='printers.PrinterItem'),
        ),
    ]
