# Generated by Django 2.0.3 on 2018-03-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer_spares', '0001_initial'),
        ('printers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerrepairjob',
            name='spares',
            field=models.ManyToManyField(to='printer_spares.Spare'),
        ),
    ]
