# Generated by Django 2.0.3 on 2018-03-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0002_printerrepairjob_spares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='name',
            field=models.CharField(max_length=512, unique=True, verbose_name='Name'),
        ),
    ]
