# Generated by Django 2.0.3 on 2018-03-26 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0003_auto_20180326_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.Device'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='image',
            field=models.ImageField(default='printer.png', upload_to='images/printers'),
        ),
    ]
