# Generated by Django 2.0.3 on 2018-03-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0006_auto_20180326_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='printerrepairjob',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
