# Generated by Django 2.0.3 on 2018-03-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0008_auto_20180326_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printeritem',
            name='inventory_number',
            field=models.CharField(max_length=32, unique=True, verbose_name='inventory number'),
        ),
    ]
