# Generated by Django 2.0.3 on 2018-03-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0009_auto_20180326_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printerchangecartridgejob',
            name='printed_sheets',
            field=models.IntegerField(blank=True, null=True, verbose_name='printed sheets'),
        ),
    ]
