# Generated by Django 2.0.3 on 2018-04-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0010_auto_20180326_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='mfp',
            field=models.BooleanField(default=False),
        ),
    ]
