# Generated by Django 2.0.3 on 2018-04-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printers', '0011_printer_mfp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printer',
            old_name='network',
            new_name='ethernet',
        ),
        migrations.AddField(
            model_name='printer',
            name='usb',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='wireless',
            field=models.BooleanField(default=False),
        ),
    ]
