# Generated by Django 2.0.3 on 2018-04-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('printers', '0013_auto_20180402_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='printeritem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
