# Generated by Django 2.0.3 on 2018-04-07 06:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('printers', '0014_printeritem_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printer',
            options={'ordering': ['name']},
        ),
    ]
