# Generated by Django 2.0.3 on 2018-04-09 14:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('printers', '0016_printeritem_office'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printer',
            options={'ordering': ['id']},
        ),
    ]
