# Generated by Django 2.0.3 on 2018-04-29 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('printers', '0017_auto_20180409_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printeritem',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.Office'),
        ),
        migrations.AlterField(
            model_name='printeritem',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.Place'),
        ),
    ]
