# Generated by Django 2.0.3 on 2018-05-04 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('devices', '0026_auto_20180504_1626'),
        ('printers', '0018_auto_20180429_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='printeritem',
            name='prefix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='devices.InventoryNumberPrefix'),
        ),
    ]
