# Generated by Django 2.0.3 on 2018-05-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('printers', '0019_printeritem_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printeritem',
            name='inventory_number',
            field=models.CharField(max_length=32, verbose_name='inventory number'),
        ),
    ]
